### ISSUE TITLE
Add scroll bar for navigating through questions on privacy-policy page

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI-ngx#107]
### Observed Behaviour
There is a scroll bar for navigating through questions on Privacy-Policy page which is not functional.

### Expected Behaviour
Add a functional scroll bar for navigating through questions.

@RishabhJain2018

**Comment by sivapalivela** [comment]
Is this issue fixed(The functional scroll bar) ?

**Comment by lunayach** [comment]
Hi @sivakumarpalivela! There was a pull request earlier to solve this issue. It's live here, https://pr-111-evalai.surge.sh/ Please see if the behaviour is desirable. If not, you could send a new PR solving it.

Otherwise, feel free to work on other issues, https://github.com/Cloud-CV/EvalAI-ngx/issues or on one of the GSoC deliverables for this year, https://github.com/Cloud-CV/GSoC-Ideas/issues/23

Looking forward to your GSoC proposal! :smile:
