### ISSUE TITLE
Selected Marker Is now showing on clicking create challange in sidebar

### ISSUE THREAD

**Issue by aloksingh3112** [Cloud-CV/EvalAI-ngx#304]
(Check one with "x" from given options)
- [ x ] Bug report
- [ ] Feature request
<img width="1396" alt="Screenshot 2020-03-20 at 11 35 23 PM" src="https://user-images.githubusercontent.com/27079355/77194261-a5451d00-6b05-11ea-8e42-5e8f851590c5.png">

**Comment by aloksingh3112** [comment]
@Sanji515 if this is fine I would like to work on this

**Comment by Kajol-Kumari** [comment]
@aloksingh3112 Thanks for the issue but when you click on "Create Challenge" it redirects you to the "Host Teams" tab as you can't host a challenge without a host team. This is the reason the "create challenge" tab not get highlighted after being clicked and instead "Host Teams" tab gets highlighted.
So, please feel free to close this one as I think this issue is not require.
